name: Verify Template
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ 'main' ]
    paths-ignore:
      - "**.md"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: blueprint-template
    steps:
      - uses: actions/checkout@v4
      - name: Install Foundry
        run: |
          curl -L https://foundry.paradigm.xyz | bash
          source /Users/runner/.bashrc
          foundryup
            - name: Add Foundry to PATH
          run: echo "${HOME}/.foundry/bin" >> $GITHUB_PATH
            - name: Verify Forge installation
          run: forge --version
      - uses: JohnPeel/cargo-generate-action@main
        with:
          name: ${{ env.PROJECT_NAME }}
          arguments: >
            --define gh-username="webb-tools"
            --define project-description="An example blueprint"
            --define project-homepage="https://webb.tools"
            --define flakes=true
            --define docker=true
            --define base-image="rustlang/rust:nightly"
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - run: |
          cp -r $PROJECT_NAME ${{ runner.temp }}/
          cd ${{ runner.temp }}/$PROJECT_NAME
          cargo check
